# This is a basic workflow to help you get started with Actions

name: testing open proxies block

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

       # Runs a single command using the runners shell
      - name: Install git
        run: sudo apt install git -y

       # Runs a single command using the runners shell
      - name: Clone the repo
        run: git clone https://github.com/fabriziosalmi/blacklist-scripts.git      
        
        # Runs a single command using the runners shell
      - name: cd to the repo folder
        run: cd blacklist-scripts

        # Runs a single command using the runners shell
      - name: change script mermissions
        run: sudo chmod +x block_proxies.sh

        # Runs a single command using the runners shell
      - name: Execute script
        run: sudo ./block_proxies.sh

